"""create initial schema

Revision ID: 7eae3a0a9627
Revises: 
Create Date: 2026-09-26 22:11:45.321481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eae3a0a9627'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(username) BETWEEN 3 AND 64', name='ck_users_username_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('api_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('api_key_cipher', sa.Text(), nullable=False),
    sa.Column('model_type', sa.String(length=64), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('check_ins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='ck_check_ins_difficulty_range'),
    sa.CheckConstraint('duration_minutes > 0', name='ck_check_ins_duration_minutes_positive'),
    sa.CheckConstraint('energy BETWEEN 1 AND 5', name='ck_check_ins_energy_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mistakes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('my_answer', sa.Text(), nullable=True),
    sa.Column('why_wrong', sa.Text(), nullable=True),
    sa.Column('correct_understanding', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("review_status IN ('pending', 'scheduled', 'done')", name='ck_mistakes_review_status_values'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('goal_date', sa.Date(), nullable=False),
    sa.Column('current_level', sa.String(length=255), nullable=False),
    sa.Column('daily_minutes', sa.Integer(), nullable=False),
    sa.Column('total_phases', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('daily_minutes > 0', name='ck_plans_daily_minutes_positive'),
    sa.CheckConstraint('total_phases BETWEEN 2 AND 12', name='ck_plans_total_phases_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("file_type IN ('pdf', 'docx', 'txt', 'md')", name='ck_user_documents_file_type_values'),
    sa.CheckConstraint('chunk_index >= 0', name='ck_user_documents_chunk_index_nonnegative'),
    sa.CheckConstraint('length(content) <= 1000', name='ck_user_documents_content_length'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'chunk_index', name='uq_user_documents_doc_chunk')
    )
    op.create_table('weekly_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('completion_rate', sa.Integer(), nullable=False),
    sa.Column('mastery_avg', sa.Integer(), nullable=False),
    sa.Column('mastery_detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completion_rate BETWEEN 0 AND 100', name='ck_weekly_reviews_completion_rate_range'),
    sa.CheckConstraint('mastery_avg BETWEEN 0 AND 100', name='ck_weekly_reviews_mastery_avg_range'),
    sa.CheckConstraint('streak_days >= 0', name='ck_weekly_reviews_streak_days_nonnegative'),
    sa.CheckConstraint('total_minutes >= 0', name='ck_weekly_reviews_total_minutes_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', 'week_end', name='uq_weekly_reviews_user_week')
    )
    op.create_table('phases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('phase_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.CheckConstraint('progress_percent BETWEEN 0 AND 100', name='ck_phases_progress_percent_range'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'phase_index', name='uq_phases_plan_phase_index')
    )
    op.create_table('daily_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('phase_id', sa.Uuid(), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('week_label', sa.String(length=8), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'done')", name='ck_daily_tasks_status_values'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_tasks')
    op.drop_table('phases')
    op.drop_table('weekly_reviews')
    op.drop_table('user_documents')
    op.drop_table('plans')
    op.drop_table('mistakes')
    op.drop_table('check_ins')
    op.drop_table('api_configs')
    op.drop_table('users')
    # ### end Alembic commands ###
